# Generated by Django 4.2.13 on 2024-05-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ko", "Korean"),
                            ("en", "English"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={"db_table": "member",},
        ),
        migrations.CreateModel(
            name="RestaurantInfo1",
            fields=[
                ("restaurant_id", models.AutoField(primary_key=True, serialize=False)),
                ("restaurant_name", models.CharField(max_length=255)),
                ("icon_path", models.CharField(max_length=255)),
            ],
            options={"db_table": "restaurant_info1",},
        ),
        migrations.CreateModel(
            name="RestaurantBookmarkCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookmark_count", models.IntegerField(default=0)),
                (
                    "restaurant_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_management.restaurantinfo1",
                    ),
                ),
            ],
            options={"db_table": "restaurant_bookmark_count",},
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookmarked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_management.member",
                    ),
                ),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member_management.restaurantinfo1",
                    ),
                ),
            ],
            options={
                "db_table": "bookmark",
                "unique_together": {("member_id", "restaurant_id")},
            },
        ),
    ]
